-- Jalankan sekali di Supabase SQL Editor.
-- Jangan pernah memasukkan SERVICE ROLE KEY ke browser.
ALTER TABLE products ADD COLUMN IF NOT EXISTS min_stock integer DEFAULT 5;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS refund_amount numeric DEFAULT 0, ADD COLUMN IF NOT EXISTS refund_items jsonb DEFAULT '[]'::jsonb, ADD COLUMN IF NOT EXISTS refund_reason text, ADD COLUMN IF NOT EXISTS refunded_at timestamptz, ADD COLUMN IF NOT EXISTS refunded_by text, ADD COLUMN IF NOT EXISTS status text DEFAULT 'completed';
CREATE TABLE IF NOT EXISTS stock_movements (id bigint generated by default as identity primary key, product_id bigint, product_name text not null, change_qty integer not null, stock_before integer not null, stock_after integer not null, movement_type text not null default 'adjustment', reason text, user_id text, user_name text, created_at timestamptz not null default now());
CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id ON stock_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_created_at ON stock_movements(created_at desc);
-- Jika RLS aktif, berikan policy SELECT/INSERT/UPDATE yang sesuai kepada frontend.
